### ISSUE TITLE
Breaking changes for the next major release

### ISSUE THREAD

**Issue by axic** [indutny/bn.js#129]
(Taking the discussion from #112 to here)

Proposed changes:
- [x] Make `.modn()` return a BN (#112)
- [x] Renaming `.strip()` to `._strip()` is a breaking change too (#105)
- [x] Maybe reviewing the constructor method(s) could lead to such a change (see #90 & #91)
- [ ] Rename `.andln()` to `.andn()` (see the README). Perhaps fold the functionality into `toArrayLike` and make `.andn()` safe in terms of working up to 53 bits
- [ ] Maybe at that stage two's complement could be made more internal (part of constructor and toString) (see #73)
- [ ] Split out the extended functions (saving destroyed bits) off `iusrhn()` into a specific shift right version, because it is only used in `MPrime.split()` and is complex.
- [ ] Remove internal functions from the BN context (good candidates are: `_countBits`, `_zeroBits`, etc. Others could be moved too with passing a `self` variable instead of using this, however that might have a speed penalty or increase?)
- [ ] Perhaps rethink naming/functionality of the following bitwise methods: `setn` (should be renamed `isetn` as it is in-place), `testn`, `maskn`, `bincn`

**Comment by axic** [comment]
I also propose to create a `v5.x` branch to merge these changes in.

**Comment by axic** [comment]
Perhaps also #107 could be discussed as part of this.

**Comment by fanatid** [comment]
Any plans regarding https://github.com/indutny/bn.js/issues/35 as part of next major release ?

**Comment by fanatid** [comment]
@indutny just would like to know your opinion about Buffer ([node](http://nodejs.org/api/buffer.html)/[browser](https://github.com/feross/buffer/)) instead Array here

**Comment by indutny** [comment]
@fanatid for what?

**Comment by fanatid** [comment]
out of curiosity...
as I understand you used Array instead Buffer for zero dependencies, why not Uint8Array for example?
if there were no question about dependencies, would you use Buffer instead Array?

**Comment by indutny** [comment]
@fanatid both Buffer and Uint8Array were slower for the purposes of bn.js . I've experimented with it several times, and at each try it was worse.

**Comment by indutny** [comment]
@fanatid additionally, allocation is a huge problem.

**Comment by fanatid** [comment]
oh, okay, so the main reason is performance? How long ago are you tested?
Array allocation work better? Maybe I'm wrong, but as I remember, Buffer allocate more then requested? (or pre-allocated buffers works in such way, at least in node)

**Comment by indutny** [comment]
I've tested it about 6 months ago, but feel free to give it another try.

Array allocation is fast as hell, while Buffer/Uint8Array generally takes more time to create and additional time to manage (GC). Pre-allocating buffers works, but it doesn't currently fit into the scheme of things, and considering that they were slower anyway - I didn't see a reason to change APIs.

**Comment by fanatid** [comment]
Thank you for explanation.
Can you publish you tests for Array/Buffer/Uint8Array comparison?

**Comment by indutny** [comment]
Something like this, I guess: https://gist.github.com/indutny/f37c466b4765e686b766b0b32557557c . Btw, just recalled that `Buffer`s can't be used for it, only `Uint32Array`

**Comment by indutny** [comment]
Updated gist to make results more fair. Should be started either as `node bench.js u` or just `node bench.js`.

**Comment by fanatid** [comment]
I think #90 #91 #141 #151 should be added to list

**Comment by indutny** [comment]
Should we do it after January 1st? cc @fanatid  @dcousens

**Comment by dcousens** [comment]
ACK,  sounds good to me,  I'll happily put some time into bumping some of the crypto-browserify packages up to the new changes.

**Comment by dcousens** [comment]
> Maybe at that stage two's complement could be made more internal (part of constructor and toString) (see #73)

Did we want to elaborate more on what this change might entail? (Aka, summarise #73)

**Comment by dcousens** [comment]
@axic how do you use `toTwos/fromTwos` to parse a DER integer?

**Comment by axic** [comment]
@dcousens luckily I am not dealing with ASN.1. `toTwos`/`fromTwos` is used within https://github.com/ethereumjs.

**Comment by indutny** [comment]
Didn't mean to close this. @dcousens what do you think about the rest of the list? Is it something that we want to address in this major bump?

**Comment by axic** [comment]
@indutny I'd pretty much like `modn` to return a BN but take a Number if possible

**Comment by dcousens** [comment]
@indutny if you don't intend to change `modn` to return a BN,  I'd remove it.

> andln

`andrn`?
What was `l`?

Is this function intentionally public?

I think the rest of the list is good,  but,  I don't have the time to do it,  and assuming you don't,  I think the changes in the last 24 hours have been fantastic.

Non-strict hex has been a liability from the get-go for me.

**Comment by indutny** [comment]
Yeah, I don't want to change it for exactly these reasons. Good call! Is the benefit of more sound API outweighs breaking changes? It would be better to deprecate it with a warning, but there is no code to do this yet.

Oh, perhaps `l` was for returning number... I guess we should rename it to `modln` then. Sincerely, I can't recall...

**Comment by indutny** [comment]
I don't mind naming it `modln` instead of `modrn`, and mentioning it in the docs. Would you care to open a PR?

**Comment by dcousens** [comment]
> I don't mind naming it modln instead of modrn, and mentioning it in the docs. Would you care to open a PR?

I suppose,  but what did `ln` mean?  `rn` is more intuitive from your explanation of `return number`.

**Comment by dcousens** [comment]
Additional breaking change request:

* Assert `str.length % 2 === 0` for base16/hex

**Comment by indutny** [comment]
I have no idea. Should we do same renaming for `andln` => `andrn` then?

-1 for hex padding. This is going to be hell of a breaking change.

**Comment by dcousens** [comment]
@indutny yes,  but,  is `andln` useful?  It only works on the first word?

**Comment by indutny** [comment]
I think it is useful.

> Unexpected padding errors have caused countless problems for libraries.

Maybe we can make it throw for just `hex`, and accept without padding for base-16?

**Comment by dcousens** [comment]
> Maybe we can make it throw for just hex, and accept without padding for base-16?

That sound reasonable.

**Comment by axic** [comment]
Here was another potential thing: Rename `toJSON`, see https://github.com/indutny/bn.js/pull/164#issuecomment-303332320

**Comment by fanatid** [comment]
@axic how you think, what `toJSON` actually should return?

**Comment by axic** [comment]
Never mind, I've only realised now that `toJSON` is potentially used by `JSON.stringify` and it should have no other use beyond that. Perhaps documenting this would be enough.

**Comment by axic** [comment]
Reviewing the release, it seems that #112 could have been more clear. Perhaps for the 6.x release then 😉
